Repository angelolab/toffy, pull requests merged in 2022-11, with the labels that each got.

#280 Compressed Tiff Files
  toffy/file_hash_test.py
  toffy/image_stitching.py
  toffy/image_utils.py
  toffy/image_utils_test.py
  toffy/normalize.py
  toffy/qc_comp.py
  toffy/rosetta.py
  toffy/rosetta_test.py
  toffy/streak_detection.py
Labels: enhancement

#281 Next Release - v0.1.1
  environment.yml
  requirements.txt
  setup.py
  toffy/image_stitching.py
  toffy/image_utils.py
  toffy/image_utils_test.py
  toffy/json_utils_test.py
  toffy/mph_comp_test.py
  toffy/mph_inspect_test.py
  toffy/normalize.py
  toffy/qc_comp.py
  toffy/qc_metrics_plots.py
  toffy/qc_metrics_plots_test.py
  toffy/rosetta.py
  toffy/rosetta_test.py
Labels: dependencies

#282 Image Utils in TMI
  requirements.txt
  toffy/file_hash_test.py
  toffy/image_stitching.py
  toffy/image_utils.py
  toffy/image_utils_test.py
  toffy/normalize.py
  toffy/qc_comp.py
  toffy/rosetta.py
  toffy/rosetta_test.py
  toffy/streak_detection.py
Labels: dependencies

#284 add tmi to environment.yml
  environment.yml
Labels: dependencies

#285 Tiled stitching for toffy
  templates/3e_stitch_images.ipynb
  toffy/image_stitching.py
  toffy/image_stitching_test.py
Labels: enhancement

#290 Skip empty json files in voltage check
  toffy/normalize.py
  toffy/normalize_test.py
Labels: bug

#286 Adding TMI
  environment.yml
  requirements.txt
  toffy/bin_extraction.py
  toffy/bin_extraction_test.py
  toffy/detector_sweep.py
  toffy/detector_sweep_test.py
  toffy/file_hash.py
  toffy/file_hash_test.py
  toffy/fov_watcher.py
  toffy/fov_watcher_test.py
  toffy/image_stitching.py
  toffy/image_stitching_test.py
  toffy/json_utils.py
  toffy/json_utils_test.py
  toffy/mibitracker_utils.py
  toffy/mph_comp.py
  toffy/mph_comp_test.py
  toffy/mph_inspect.py
  toffy/mph_inspect_test.py
  toffy/normalize.py
  toffy/normalize_test.py
  toffy/normalize_test_cases.py
  toffy/panel_utils.py
  toffy/panel_utils_test.py
  toffy/qc_comp.py
  toffy/qc_comp_test.py
  toffy/qc_metrics_plots.py
  toffy/qc_metrics_plots_test.py
  toffy/reorg.py
  toffy/reorg_test.py
  toffy/rosetta.py
  toffy/rosetta_test.py
  toffy/rosetta_test_cases.py
  toffy/streak_detection.py
  toffy/streak_detection_test.py
  toffy/test_utils.py
  toffy/tiling_utils.py
  toffy/tiling_utils_test.py
  toffy/tiling_utils_test_cases.py
  toffy/watcher_callbacks.py
  toffy/watcher_callbacks_test.py
Labels: dependencies

#295 Substituted Ark imports with TMI in the Jupyter Notebooks
  templates/1_set_up_toffy.ipynb
  templates/3c_generate_qc_metrics.ipynb
  templates/3d_compute_median_pulse_height.ipynb
  templates/4a_compensate_image_data.ipynb
  templates/4b_normalize_image_data.ipynb
  templates/5_rename_and_reorganize.ipynb
Labels: dependencies

#297 Conda Environment - scikit-learn & seaborn
  environment.yml
Labels: dependencies
