Repository angelolab/toffy, pull requests merged in 2022-08, with the labels that each got.

#176 3b and 3d documentation updates
  templates/3a_monitor_MIBI_run.ipynb
  templates/3b_extract_images_from_bin.ipynb
  templates/3d_compute_median_pulse_height.ipynb
  templates/per_tof_histograms.ipynb
  toffy/bin_extraction.py
  toffy/bin_extraction_test.py
  toffy/mph_comp.py
  toffy/watcher_callbacks.py
  toffy/watcher_callbacks_test.py
Labels: documentation

#175 Notebook 1 - Documentation Improvements
  templates/1_set_up_toffy.ipynb
Labels: documentation

#182 Added the location of the Optical Image File in the Notebook
  templates/2_create_tma_mibi_run.ipynb
Labels: bug, documentation

#200 Toffy Pipeline Flowchart
  README.md
  templates/img/toffy_processing.png
Labels: documentation

#177 Notebook 4a - Documentation Improvements
  templates/.DS_Store
  templates/4a_compensate_image_data.ipynb
  templates/img/CD11c_post_rosetta_cropped.png
  templates/img/CD11c_pre_rosetta_cropped.png
Labels: documentation

#204 Added Step 3e to the pipeline flowchart
  templates/img/toffy_processing.png
Labels: documentation

#206 Added `.DS_Store` in the `.gitignore`
  .gitignore
  templates/.DS_Store
Labels: enhancement

#193 Watcher hidden files
  toffy/bin_extraction.py
  toffy/bin_extraction_test.py
  toffy/fov_watcher.py
  toffy/fov_watcher_test.py
  toffy/qc_comp.py
Labels: bug

#190 Update readme with directory structure
  README.md
  templates/1_set_up_toffy.ipynb
  templates/2_create_tiled_mibi_run.ipynb
  templates/2_create_tma_mibi_run.ipynb
  templates/3a_monitor_MIBI_run.ipynb
  templates/3b_extract_images_from_bin.ipynb
  templates/3c_generate_qc_metrics.ipynb
  templates/3d_compute_median_pulse_height.ipynb
  templates/3e_stitch_images.ipynb
  templates/4a_compensate_image_data.ipynb
  templates/4b_normalize_image_data.ipynb
  templates/5_rename_and_reorganize.ipynb
  templates/img/C_dirs.png
  templates/img/D_dirs.png
  templates/img/quick_access.gif
Labels: documentation

#202 Panel conversion implementation
  README.md
  files/example_panel_file.csv
  templates/3a_monitor_MIBI_run.ipynb
  templates/3b_extract_images_from_bin.ipynb
  templates/3c_generate_qc_metrics.ipynb
  templates/3e_stitch_images.ipynb
  templates/4b_normalize_image_data.ipynb
  templates/img/panel_download.png
  toffy/panel_utils.py
  toffy/panel_utils_test.py
Labels: enhancement

#225 Catches tempdir cleanup error
  toffy/fov_watcher_test.py
Labels: bug

#223 Create release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement
